---
  dataset: "weather"
  is_regression: True
  random_feat_split: True
  bound_dist: [3]
  is_bound_percent: False
  forward_batch_size: 4096
  # Ensemble parameters
  alt_type: "lasso"
  n_disjoint_models: 25
  ssl_degree: 1
  # Lasso params
  model_params:
    alpha: 3.16E-3
    max_iter: 1E4
    tol: 1e-03
